#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_SEMI = 2,
  anon_sym_COMMA = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LT = 6,
  anon_sym_GT = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_SLASH = 10,
  anon_sym_DOT = 11,
  anon_sym_DASH = 12,
  anon_sym_PLUS = 13,
  sym_identifier = 14,
  anon_sym_SQUOTE = 15,
  aux_sym_single_string_token1 = 16,
  anon_sym_DQUOTE = 17,
  aux_sym_double_string_token1 = 18,
  aux_sym_escape_sequence_token1 = 19,
  aux_sym_escape_sequence_token2 = 20,
  aux_sym_escape_sequence_token3 = 21,
  aux_sym_escape_sequence_token4 = 22,
  aux_sym_escape_sequence_token5 = 23,
  anon_sym_0 = 24,
  aux_sym_decimal_lit_token1 = 25,
  sym_octal_lit = 26,
  sym_hex_lit = 27,
  sym_float_lit = 28,
  aux_sym_exponent_token1 = 29,
  aux_sym_exponent_token2 = 30,
  aux_sym_exponent_token3 = 31,
  anon_sym_POUND = 32,
  aux_sym_comment_token1 = 33,
  sym_source_file = 34,
  sym_field = 35,
  sym_message_field = 36,
  sym_scalar_field = 37,
  sym_message_value = 38,
  sym_message_body = 39,
  sym_message_list = 40,
  sym_field_name = 41,
  sym_extension_name = 42,
  sym_any_name = 43,
  sym_type_name = 44,
  sym_domain = 45,
  sym_scalar_value = 46,
  sym_scalar_list = 47,
  sym_signed_identifier = 48,
  sym_string = 49,
  sym_single_string = 50,
  sym_double_string = 51,
  sym_escape_sequence = 52,
  sym_number = 53,
  sym_int_lit = 54,
  sym_decimal_lit = 55,
  sym_comment = 56,
  aux_sym_source_file_repeat1 = 57,
  aux_sym_message_list_repeat1 = 58,
  aux_sym_type_name_repeat1 = 59,
  aux_sym_scalar_value_repeat1 = 60,
  aux_sym_scalar_list_repeat1 = 61,
  aux_sym_single_string_repeat1 = 62,
  aux_sym_double_string_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SLASH] = "/",
  [anon_sym_DOT] = ".",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [sym_identifier] = "identifier",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_single_string_token1] = "single_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_double_string_token1] = "double_string_token1",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [aux_sym_escape_sequence_token2] = "escape_sequence_token2",
  [aux_sym_escape_sequence_token3] = "escape_sequence_token3",
  [aux_sym_escape_sequence_token4] = "escape_sequence_token4",
  [aux_sym_escape_sequence_token5] = "escape_sequence_token5",
  [anon_sym_0] = "0",
  [aux_sym_decimal_lit_token1] = "decimal_lit_token1",
  [sym_octal_lit] = "octal_lit",
  [sym_hex_lit] = "hex_lit",
  [sym_float_lit] = "float_lit",
  [aux_sym_exponent_token1] = "exponent_token1",
  [aux_sym_exponent_token2] = "exponent_token2",
  [aux_sym_exponent_token3] = "exponent_token3",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym_field] = "field",
  [sym_message_field] = "message_field",
  [sym_scalar_field] = "scalar_field",
  [sym_message_value] = "message_value",
  [sym_message_body] = "message_body",
  [sym_message_list] = "message_list",
  [sym_field_name] = "field_name",
  [sym_extension_name] = "extension_name",
  [sym_any_name] = "any_name",
  [sym_type_name] = "type_name",
  [sym_domain] = "domain",
  [sym_scalar_value] = "scalar_value",
  [sym_scalar_list] = "scalar_list",
  [sym_signed_identifier] = "signed_identifier",
  [sym_string] = "string",
  [sym_single_string] = "single_string",
  [sym_double_string] = "double_string",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_int_lit] = "int_lit",
  [sym_decimal_lit] = "decimal_lit",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_message_list_repeat1] = "message_list_repeat1",
  [aux_sym_type_name_repeat1] = "type_name_repeat1",
  [aux_sym_scalar_value_repeat1] = "scalar_value_repeat1",
  [aux_sym_scalar_list_repeat1] = "scalar_list_repeat1",
  [aux_sym_single_string_repeat1] = "single_string_repeat1",
  [aux_sym_double_string_repeat1] = "double_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_identifier] = sym_identifier,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_single_string_token1] = aux_sym_single_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_double_string_token1] = aux_sym_double_string_token1,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [aux_sym_escape_sequence_token2] = aux_sym_escape_sequence_token2,
  [aux_sym_escape_sequence_token3] = aux_sym_escape_sequence_token3,
  [aux_sym_escape_sequence_token4] = aux_sym_escape_sequence_token4,
  [aux_sym_escape_sequence_token5] = aux_sym_escape_sequence_token5,
  [anon_sym_0] = anon_sym_0,
  [aux_sym_decimal_lit_token1] = aux_sym_decimal_lit_token1,
  [sym_octal_lit] = sym_octal_lit,
  [sym_hex_lit] = sym_hex_lit,
  [sym_float_lit] = sym_float_lit,
  [aux_sym_exponent_token1] = aux_sym_exponent_token1,
  [aux_sym_exponent_token2] = aux_sym_exponent_token2,
  [aux_sym_exponent_token3] = aux_sym_exponent_token3,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_field] = sym_field,
  [sym_message_field] = sym_message_field,
  [sym_scalar_field] = sym_scalar_field,
  [sym_message_value] = sym_message_value,
  [sym_message_body] = sym_message_body,
  [sym_message_list] = sym_message_list,
  [sym_field_name] = sym_field_name,
  [sym_extension_name] = sym_extension_name,
  [sym_any_name] = sym_any_name,
  [sym_type_name] = sym_type_name,
  [sym_domain] = sym_domain,
  [sym_scalar_value] = sym_scalar_value,
  [sym_scalar_list] = sym_scalar_list,
  [sym_signed_identifier] = sym_signed_identifier,
  [sym_string] = sym_string,
  [sym_single_string] = sym_single_string,
  [sym_double_string] = sym_double_string,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_int_lit] = sym_int_lit,
  [sym_decimal_lit] = sym_decimal_lit,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_message_list_repeat1] = aux_sym_message_list_repeat1,
  [aux_sym_type_name_repeat1] = aux_sym_type_name_repeat1,
  [aux_sym_scalar_value_repeat1] = aux_sym_scalar_value_repeat1,
  [aux_sym_scalar_list_repeat1] = aux_sym_scalar_list_repeat1,
  [aux_sym_single_string_repeat1] = aux_sym_single_string_repeat1,
  [aux_sym_double_string_repeat1] = aux_sym_double_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_single_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_double_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token5] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_decimal_lit_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_octal_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_float_lit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_exponent_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exponent_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exponent_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_message_field] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_field] = {
    .visible = true,
    .named = true,
  },
  [sym_message_value] = {
    .visible = true,
    .named = true,
  },
  [sym_message_body] = {
    .visible = true,
    .named = true,
  },
  [sym_message_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_extension_name] = {
    .visible = true,
    .named = true,
  },
  [sym_any_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_value] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_list] = {
    .visible = true,
    .named = true,
  },
  [sym_signed_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_string] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_int_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scalar_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scalar_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 41,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
};

static TSCharacterRange aux_sym_escape_sequence_token1_character_set_1[] = {
  {'"', '"'}, {'\'', '\''}, {'?', '?'}, {'\\', '\\'}, {'a', 'b'}, {'f', 'f'}, {'n', 'n'}, {'r', 'r'},
  {'t', 't'}, {'v', 'v'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 43,
        '#', 65,
        '\'', 40,
        '+', 38,
        ',', 27,
        '-', 37,
        '.', 36,
        '/', 34,
        '0', 54,
        ':', 25,
        ';', 26,
        '<', 30,
        '>', 31,
        '[', 32,
        '\\', 5,
        ']', 33,
        '{', 28,
        '}', 29,
        'E', 39,
        'e', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == ']') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(62);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == 'U') ADVANCE(22);
      if (lookahead == 'u') ADVANCE(17);
      if (lookahead == 'x') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(49);
      if (set_contains(aux_sym_escape_sequence_token1_character_set_1, 10, lookahead)) ADVANCE(46);
      END_STATE();
    case 6:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 43,
        '#', 65,
        '\'', 40,
        '+', 38,
        ',', 27,
        '-', 37,
        '.', 7,
        '0', 55,
        ';', 26,
        '<', 30,
        '>', 31,
        '[', 32,
        ']', 33,
        '{', 28,
        '}', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_single_string_token1);
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_single_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_double_string_token1);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_double_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token2);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token2);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token2);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token3);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token4);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token5);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_0);
      ADVANCE_MAP(
        '.', 62,
        'E', 6,
        'e', 6,
        'F', 60,
        'f', 60,
        'X', 9,
        'x', 9,
        '8', 64,
        '9', 64,
      );
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_0);
      ADVANCE_MAP(
        '.', 62,
        'E', 6,
        'e', 6,
        'F', 60,
        'f', 60,
        'X', 9,
        'x', 9,
        '8', 4,
        '9', 4,
      );
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(58);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_decimal_lit_token1);
      if (lookahead == '.') ADVANCE(62);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_octal_lit);
      if (lookahead == '.') ADVANCE(62);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(60);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_octal_lit);
      if (lookahead == '.') ADVANCE(62);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(60);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_hex_lit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_float_lit);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_float_lit);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_float_lit);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_float_lit);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_exponent_token3);
      if (lookahead == '.') ADVANCE(62);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(45);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(68);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 23},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 23},
  [8] = {.lex_state = 23},
  [9] = {.lex_state = 23},
  [10] = {.lex_state = 23},
  [11] = {.lex_state = 23},
  [12] = {.lex_state = 23},
  [13] = {.lex_state = 23},
  [14] = {.lex_state = 23},
  [15] = {.lex_state = 23},
  [16] = {.lex_state = 23},
  [17] = {.lex_state = 23},
  [18] = {.lex_state = 23},
  [19] = {.lex_state = 23},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 23},
  [27] = {.lex_state = 23},
  [28] = {.lex_state = 23},
  [29] = {.lex_state = 23},
  [30] = {.lex_state = 23},
  [31] = {.lex_state = 23},
  [32] = {.lex_state = 23},
  [33] = {.lex_state = 23},
  [34] = {.lex_state = 23},
  [35] = {.lex_state = 23},
  [36] = {.lex_state = 23},
  [37] = {.lex_state = 23},
  [38] = {.lex_state = 23},
  [39] = {.lex_state = 23},
  [40] = {.lex_state = 23},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 23},
  [43] = {.lex_state = 23},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 23},
  [47] = {.lex_state = 23},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 23},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 23},
  [52] = {.lex_state = 23},
  [53] = {.lex_state = 23},
  [54] = {.lex_state = 23},
  [55] = {.lex_state = 23},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 23},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 23},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 69},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 23},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_escape_sequence_token1] = ACTIONS(1),
    [aux_sym_escape_sequence_token2] = ACTIONS(1),
    [aux_sym_escape_sequence_token3] = ACTIONS(1),
    [aux_sym_escape_sequence_token4] = ACTIONS(1),
    [aux_sym_escape_sequence_token5] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [aux_sym_decimal_lit_token1] = ACTIONS(1),
    [sym_octal_lit] = ACTIONS(1),
    [sym_hex_lit] = ACTIONS(1),
    [sym_float_lit] = ACTIONS(1),
    [aux_sym_exponent_token1] = ACTIONS(1),
    [aux_sym_exponent_token2] = ACTIONS(1),
    [aux_sym_exponent_token3] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(85),
    [sym_field] = STATE(55),
    [sym_message_field] = STATE(52),
    [sym_scalar_field] = STATE(52),
    [sym_field_name] = STATE(50),
    [sym_extension_name] = STATE(58),
    [sym_any_name] = STATE(58),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 21,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym_octal_lit,
    ACTIONS(29), 1,
      sym_hex_lit,
    ACTIONS(31), 1,
      sym_float_lit,
    STATE(2), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_scalar_value_repeat1,
    STATE(17), 1,
      sym_string,
    STATE(31), 1,
      sym_decimal_lit,
    STATE(32), 1,
      sym_int_lit,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 2,
      anon_sym_0,
      aux_sym_decimal_lit_token1,
    STATE(16), 2,
      sym_single_string,
      sym_double_string,
    STATE(28), 2,
      sym_signed_identifier,
      sym_number,
    STATE(35), 2,
      sym_scalar_value,
      sym_scalar_list,
    STATE(42), 2,
      sym_message_value,
      sym_message_list,
  [70] = 21,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym_octal_lit,
    ACTIONS(29), 1,
      sym_hex_lit,
    ACTIONS(31), 1,
      sym_float_lit,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(3), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_scalar_value_repeat1,
    STATE(17), 1,
      sym_string,
    STATE(31), 1,
      sym_decimal_lit,
    STATE(32), 1,
      sym_int_lit,
    STATE(72), 1,
      sym_scalar_value,
    STATE(74), 1,
      sym_message_value,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 2,
      anon_sym_0,
      aux_sym_decimal_lit_token1,
    STATE(16), 2,
      sym_single_string,
      sym_double_string,
    STATE(28), 2,
      sym_signed_identifier,
      sym_number,
  [138] = 18,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym_octal_lit,
    ACTIONS(29), 1,
      sym_hex_lit,
    ACTIONS(31), 1,
      sym_float_lit,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    STATE(4), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_scalar_value_repeat1,
    STATE(17), 1,
      sym_string,
    STATE(31), 1,
      sym_decimal_lit,
    STATE(32), 1,
      sym_int_lit,
    STATE(77), 1,
      sym_scalar_value,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 2,
      anon_sym_0,
      aux_sym_decimal_lit_token1,
    STATE(16), 2,
      sym_single_string,
      sym_double_string,
    STATE(28), 2,
      sym_signed_identifier,
      sym_number,
  [197] = 18,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym_octal_lit,
    ACTIONS(29), 1,
      sym_hex_lit,
    ACTIONS(31), 1,
      sym_float_lit,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    STATE(5), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_scalar_value_repeat1,
    STATE(17), 1,
      sym_string,
    STATE(31), 1,
      sym_decimal_lit,
    STATE(32), 1,
      sym_int_lit,
    STATE(77), 1,
      sym_scalar_value,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 2,
      anon_sym_0,
      aux_sym_decimal_lit_token1,
    STATE(16), 2,
      sym_single_string,
      sym_double_string,
    STATE(28), 2,
      sym_signed_identifier,
      sym_number,
  [256] = 17,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym_octal_lit,
    ACTIONS(29), 1,
      sym_hex_lit,
    ACTIONS(31), 1,
      sym_float_lit,
    STATE(6), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_scalar_value_repeat1,
    STATE(17), 1,
      sym_string,
    STATE(31), 1,
      sym_decimal_lit,
    STATE(32), 1,
      sym_int_lit,
    STATE(77), 1,
      sym_scalar_value,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 2,
      anon_sym_0,
      aux_sym_decimal_lit_token1,
    STATE(16), 2,
      sym_single_string,
      sym_double_string,
    STATE(28), 2,
      sym_signed_identifier,
      sym_number,
  [312] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      anon_sym_SQUOTE,
    ACTIONS(44), 1,
      anon_sym_DQUOTE,
    STATE(17), 1,
      sym_string,
    STATE(7), 2,
      sym_comment,
      aux_sym_scalar_value_repeat1,
    STATE(16), 2,
      sym_single_string,
      sym_double_string,
    ACTIONS(39), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [343] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(7), 1,
      aux_sym_scalar_value_repeat1,
    STATE(8), 1,
      sym_comment,
    STATE(17), 1,
      sym_string,
    STATE(16), 2,
      sym_single_string,
      sym_double_string,
    ACTIONS(47), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [376] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(54), 1,
      sym_identifier,
    STATE(50), 1,
      sym_field_name,
    STATE(55), 1,
      sym_field,
    STATE(9), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(52), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(58), 2,
      sym_extension_name,
      sym_any_name,
    ACTIONS(49), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_GT,
  [409] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_identifier,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
    STATE(10), 1,
      sym_comment,
    STATE(50), 1,
      sym_field_name,
    STATE(55), 1,
      sym_field,
    ACTIONS(57), 2,
      anon_sym_RBRACE,
      anon_sym_GT,
    STATE(52), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(58), 2,
      sym_extension_name,
      sym_any_name,
  [443] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(11), 1,
      sym_comment,
    STATE(50), 1,
      sym_field_name,
    STATE(55), 1,
      sym_field,
    STATE(80), 1,
      sym_message_body,
    STATE(52), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(58), 2,
      sym_extension_name,
      sym_any_name,
  [479] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_GT,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(12), 1,
      sym_comment,
    STATE(50), 1,
      sym_field_name,
    STATE(55), 1,
      sym_field,
    STATE(79), 1,
      sym_message_body,
    STATE(52), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(58), 2,
      sym_extension_name,
      sym_any_name,
  [515] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(13), 1,
      sym_comment,
    ACTIONS(61), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [534] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(14), 1,
      sym_comment,
    ACTIONS(63), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [553] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
    STATE(15), 1,
      sym_comment,
    STATE(50), 1,
      sym_field_name,
    STATE(55), 1,
      sym_field,
    STATE(52), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(58), 2,
      sym_extension_name,
      sym_any_name,
  [586] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(16), 1,
      sym_comment,
    ACTIONS(67), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [605] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(17), 1,
      sym_comment,
    ACTIONS(69), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [624] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(18), 1,
      sym_comment,
    ACTIONS(71), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [643] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(19), 1,
      sym_comment,
    ACTIONS(73), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [662] = 7,
    ACTIONS(75), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      aux_sym_double_string_token1,
    ACTIONS(81), 1,
      anon_sym_POUND,
    STATE(20), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym_double_string_repeat1,
    STATE(48), 1,
      sym_escape_sequence,
    ACTIONS(79), 5,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [688] = 6,
    ACTIONS(81), 1,
      anon_sym_POUND,
    ACTIONS(83), 1,
      anon_sym_DQUOTE,
    ACTIONS(85), 1,
      aux_sym_double_string_token1,
    STATE(48), 1,
      sym_escape_sequence,
    STATE(21), 2,
      sym_comment,
      aux_sym_double_string_repeat1,
    ACTIONS(88), 5,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [712] = 7,
    ACTIONS(77), 1,
      aux_sym_double_string_token1,
    ACTIONS(81), 1,
      anon_sym_POUND,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
    STATE(21), 1,
      aux_sym_double_string_repeat1,
    STATE(22), 1,
      sym_comment,
    STATE(48), 1,
      sym_escape_sequence,
    ACTIONS(79), 5,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [738] = 6,
    ACTIONS(81), 1,
      anon_sym_POUND,
    ACTIONS(93), 1,
      anon_sym_SQUOTE,
    ACTIONS(95), 1,
      aux_sym_single_string_token1,
    STATE(44), 1,
      sym_escape_sequence,
    STATE(23), 2,
      sym_comment,
      aux_sym_single_string_repeat1,
    ACTIONS(98), 5,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [762] = 7,
    ACTIONS(81), 1,
      anon_sym_POUND,
    ACTIONS(101), 1,
      anon_sym_SQUOTE,
    ACTIONS(103), 1,
      aux_sym_single_string_token1,
    STATE(23), 1,
      aux_sym_single_string_repeat1,
    STATE(24), 1,
      sym_comment,
    STATE(44), 1,
      sym_escape_sequence,
    ACTIONS(105), 5,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [788] = 7,
    ACTIONS(81), 1,
      anon_sym_POUND,
    ACTIONS(103), 1,
      aux_sym_single_string_token1,
    ACTIONS(107), 1,
      anon_sym_SQUOTE,
    STATE(24), 1,
      aux_sym_single_string_repeat1,
    STATE(25), 1,
      sym_comment,
    STATE(44), 1,
      sym_escape_sequence,
    ACTIONS(105), 5,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [814] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym_comment,
    ACTIONS(109), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [831] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(111), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [848] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(28), 1,
      sym_comment,
    ACTIONS(47), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [865] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(29), 1,
      sym_comment,
    ACTIONS(113), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [882] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(30), 1,
      sym_comment,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [899] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(31), 1,
      sym_comment,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [916] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(32), 1,
      sym_comment,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [933] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(33), 1,
      sym_comment,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [950] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      sym_octal_lit,
    ACTIONS(29), 1,
      sym_hex_lit,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym_float_lit,
    STATE(29), 1,
      sym_int_lit,
    STATE(31), 1,
      sym_decimal_lit,
    STATE(34), 1,
      sym_comment,
    ACTIONS(25), 2,
      anon_sym_0,
      aux_sym_decimal_lit_token1,
  [979] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(35), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [997] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(36), 1,
      sym_comment,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1013] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(37), 1,
      sym_comment,
    ACTIONS(133), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1029] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(38), 1,
      sym_comment,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1045] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(39), 1,
      sym_comment,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1061] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(40), 1,
      sym_comment,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1077] = 3,
    ACTIONS(81), 1,
      anon_sym_POUND,
    STATE(41), 1,
      sym_comment,
    ACTIONS(139), 7,
      anon_sym_DQUOTE,
      aux_sym_double_string_token1,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [1093] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(42), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1111] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(43), 1,
      sym_comment,
    ACTIONS(145), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1127] = 3,
    ACTIONS(81), 1,
      anon_sym_POUND,
    STATE(44), 1,
      sym_comment,
    ACTIONS(147), 7,
      anon_sym_SQUOTE,
      aux_sym_single_string_token1,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [1143] = 3,
    ACTIONS(81), 1,
      anon_sym_POUND,
    STATE(45), 1,
      sym_comment,
    ACTIONS(139), 7,
      anon_sym_SQUOTE,
      aux_sym_single_string_token1,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [1159] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(46), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1177] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(47), 1,
      sym_comment,
    ACTIONS(153), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1193] = 3,
    ACTIONS(81), 1,
      anon_sym_POUND,
    STATE(48), 1,
      sym_comment,
    ACTIONS(155), 7,
      anon_sym_DQUOTE,
      aux_sym_double_string_token1,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
      aux_sym_escape_sequence_token4,
      aux_sym_escape_sequence_token5,
  [1209] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(49), 1,
      sym_comment,
    ACTIONS(157), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1225] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(159), 1,
      anon_sym_COLON,
    ACTIONS(161), 1,
      anon_sym_LBRACK,
    STATE(50), 1,
      sym_comment,
    STATE(46), 2,
      sym_message_value,
      sym_message_list,
  [1248] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(51), 1,
      sym_comment,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1262] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(52), 1,
      sym_comment,
    ACTIONS(165), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1276] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(53), 1,
      sym_comment,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1290] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(54), 1,
      sym_comment,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1304] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(55), 1,
      sym_comment,
    ACTIONS(169), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [1318] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(173), 1,
      anon_sym_DOT,
    ACTIONS(171), 2,
      anon_sym_RBRACK,
      anon_sym_SLASH,
    STATE(56), 2,
      sym_comment,
      aux_sym_type_name_repeat1,
  [1333] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(57), 1,
      sym_comment,
    ACTIONS(176), 4,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LBRACK,
  [1346] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(58), 1,
      sym_comment,
    ACTIONS(178), 4,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LBRACK,
  [1359] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(180), 1,
      anon_sym_RBRACK,
    ACTIONS(182), 1,
      anon_sym_SLASH,
    ACTIONS(184), 1,
      anon_sym_DOT,
    STATE(59), 1,
      sym_comment,
    STATE(62), 1,
      aux_sym_type_name_repeat1,
  [1378] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      sym_comment,
    STATE(76), 1,
      sym_message_value,
  [1397] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(188), 1,
      anon_sym_RBRACK,
    STATE(61), 1,
      sym_comment,
    STATE(74), 1,
      sym_message_value,
  [1416] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(184), 1,
      anon_sym_DOT,
    ACTIONS(190), 1,
      anon_sym_RBRACK,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    STATE(56), 1,
      aux_sym_type_name_repeat1,
    STATE(62), 1,
      sym_comment,
  [1435] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(194), 1,
      anon_sym_RBRACK,
    STATE(63), 1,
      sym_comment,
    STATE(76), 1,
      sym_message_value,
  [1454] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(64), 1,
      sym_comment,
    ACTIONS(196), 4,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LBRACK,
  [1467] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_RBRACK,
    STATE(65), 2,
      sym_comment,
      aux_sym_message_list_repeat1,
  [1481] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(66), 1,
      sym_comment,
    ACTIONS(171), 3,
      anon_sym_RBRACK,
      anon_sym_SLASH,
      anon_sym_DOT,
  [1493] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(194), 1,
      anon_sym_RBRACK,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_message_list_repeat1,
    STATE(67), 1,
      sym_comment,
  [1509] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(184), 1,
      anon_sym_DOT,
    ACTIONS(190), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      aux_sym_type_name_repeat1,
    STATE(68), 1,
      sym_comment,
  [1525] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(205), 1,
      sym_identifier,
    STATE(69), 1,
      sym_comment,
    STATE(81), 1,
      sym_type_name,
    STATE(83), 1,
      sym_domain,
  [1541] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT,
    STATE(70), 1,
      sym_comment,
    STATE(76), 1,
      sym_message_value,
  [1557] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      sym_comment,
    STATE(73), 1,
      aux_sym_scalar_list_repeat1,
  [1573] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    ACTIONS(211), 1,
      anon_sym_RBRACK,
    STATE(71), 1,
      aux_sym_scalar_list_repeat1,
    STATE(72), 1,
      sym_comment,
  [1589] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(216), 1,
      anon_sym_RBRACK,
    STATE(73), 2,
      sym_comment,
      aux_sym_scalar_list_repeat1,
  [1603] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(218), 1,
      anon_sym_COMMA,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
    STATE(67), 1,
      aux_sym_message_list_repeat1,
    STATE(74), 1,
      sym_comment,
  [1619] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(180), 1,
      anon_sym_RBRACK,
    ACTIONS(184), 1,
      anon_sym_DOT,
    STATE(68), 1,
      aux_sym_type_name_repeat1,
    STATE(75), 1,
      sym_comment,
  [1635] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(76), 1,
      sym_comment,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1646] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(77), 1,
      sym_comment,
    ACTIONS(216), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1657] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(222), 1,
      sym_identifier,
    STATE(78), 1,
      sym_comment,
    STATE(86), 1,
      sym_type_name,
  [1670] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(224), 1,
      anon_sym_GT,
    STATE(79), 1,
      sym_comment,
  [1680] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(224), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_comment,
  [1690] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(226), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym_comment,
  [1700] = 3,
    ACTIONS(81), 1,
      anon_sym_POUND,
    ACTIONS(228), 1,
      aux_sym_comment_token1,
    STATE(82), 1,
      sym_comment,
  [1710] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(230), 1,
      anon_sym_SLASH,
    STATE(83), 1,
      sym_comment,
  [1720] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(232), 1,
      sym_identifier,
    STATE(84), 1,
      sym_comment,
  [1730] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(234), 1,
      ts_builtin_sym_end,
    STATE(85), 1,
      sym_comment,
  [1740] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(236), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      sym_comment,
  [1750] = 1,
    ACTIONS(238), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 70,
  [SMALL_STATE(4)] = 138,
  [SMALL_STATE(5)] = 197,
  [SMALL_STATE(6)] = 256,
  [SMALL_STATE(7)] = 312,
  [SMALL_STATE(8)] = 343,
  [SMALL_STATE(9)] = 376,
  [SMALL_STATE(10)] = 409,
  [SMALL_STATE(11)] = 443,
  [SMALL_STATE(12)] = 479,
  [SMALL_STATE(13)] = 515,
  [SMALL_STATE(14)] = 534,
  [SMALL_STATE(15)] = 553,
  [SMALL_STATE(16)] = 586,
  [SMALL_STATE(17)] = 605,
  [SMALL_STATE(18)] = 624,
  [SMALL_STATE(19)] = 643,
  [SMALL_STATE(20)] = 662,
  [SMALL_STATE(21)] = 688,
  [SMALL_STATE(22)] = 712,
  [SMALL_STATE(23)] = 738,
  [SMALL_STATE(24)] = 762,
  [SMALL_STATE(25)] = 788,
  [SMALL_STATE(26)] = 814,
  [SMALL_STATE(27)] = 831,
  [SMALL_STATE(28)] = 848,
  [SMALL_STATE(29)] = 865,
  [SMALL_STATE(30)] = 882,
  [SMALL_STATE(31)] = 899,
  [SMALL_STATE(32)] = 916,
  [SMALL_STATE(33)] = 933,
  [SMALL_STATE(34)] = 950,
  [SMALL_STATE(35)] = 979,
  [SMALL_STATE(36)] = 997,
  [SMALL_STATE(37)] = 1013,
  [SMALL_STATE(38)] = 1029,
  [SMALL_STATE(39)] = 1045,
  [SMALL_STATE(40)] = 1061,
  [SMALL_STATE(41)] = 1077,
  [SMALL_STATE(42)] = 1093,
  [SMALL_STATE(43)] = 1111,
  [SMALL_STATE(44)] = 1127,
  [SMALL_STATE(45)] = 1143,
  [SMALL_STATE(46)] = 1159,
  [SMALL_STATE(47)] = 1177,
  [SMALL_STATE(48)] = 1193,
  [SMALL_STATE(49)] = 1209,
  [SMALL_STATE(50)] = 1225,
  [SMALL_STATE(51)] = 1248,
  [SMALL_STATE(52)] = 1262,
  [SMALL_STATE(53)] = 1276,
  [SMALL_STATE(54)] = 1290,
  [SMALL_STATE(55)] = 1304,
  [SMALL_STATE(56)] = 1318,
  [SMALL_STATE(57)] = 1333,
  [SMALL_STATE(58)] = 1346,
  [SMALL_STATE(59)] = 1359,
  [SMALL_STATE(60)] = 1378,
  [SMALL_STATE(61)] = 1397,
  [SMALL_STATE(62)] = 1416,
  [SMALL_STATE(63)] = 1435,
  [SMALL_STATE(64)] = 1454,
  [SMALL_STATE(65)] = 1467,
  [SMALL_STATE(66)] = 1481,
  [SMALL_STATE(67)] = 1493,
  [SMALL_STATE(68)] = 1509,
  [SMALL_STATE(69)] = 1525,
  [SMALL_STATE(70)] = 1541,
  [SMALL_STATE(71)] = 1557,
  [SMALL_STATE(72)] = 1573,
  [SMALL_STATE(73)] = 1589,
  [SMALL_STATE(74)] = 1603,
  [SMALL_STATE(75)] = 1619,
  [SMALL_STATE(76)] = 1635,
  [SMALL_STATE(77)] = 1646,
  [SMALL_STATE(78)] = 1657,
  [SMALL_STATE(79)] = 1670,
  [SMALL_STATE(80)] = 1680,
  [SMALL_STATE(81)] = 1690,
  [SMALL_STATE(82)] = 1700,
  [SMALL_STATE(83)] = 1710,
  [SMALL_STATE(84)] = 1720,
  [SMALL_STATE(85)] = 1730,
  [SMALL_STATE(86)] = 1740,
  [SMALL_STATE(87)] = 1750,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scalar_value_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scalar_value_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scalar_value_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_value, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_body, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scalar_value_repeat1, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decimal_lit, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_lit, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signed_identifier, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 5, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_name, 5, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_name, 3, 0, 0),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [234] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_textproto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
